ktor:
    application:
        modules:
            - com.locationapp.ApplicationKt.module
    deployment:
        port: 8080
jwt:
  domain: "https://jwt-provider-domain/"
  issuer: "http://localhost:8080"
  audience: "http://localhost:8080/audience"
  realm: "locationapp"
  privateKey: ${jwt_pk}
  publicKey: ${jwt_Pk}
postgres:
  url: "jdbc:postgresql://localhost/default"
  user: ${postgres_user}
  password: ${postgres_pass}